language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=0
      php: 7.2
  include:
    - env: TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 7.1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
    - php: 7.2

notifications:
  email:
    recipients:
      - stefan.masztalerz@aoe.com
    on_success: always
    on_failure: always

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Installs TYPO3
  - composer require --dev typo3/cms=$TYPO3_VERSION;
  # Restore composer.json
  - git checkout composer.json;
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml
  - export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'

script:
  - >
    echo "Running unit tests";
    if [[ "$COVERAGE" == "0" ]]; then
      php .Build/bin/phpunit --colors -c $UNIT_XML Tests/
    else
      echo "Running unit tests";
      php .Build/bin/phpunit --whitelist Classes/ --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/

      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    fi

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
