language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TYPO3_BRANCH=master COVERAGE=0
  - TYPO3_BRANCH=TYPO3_6-2 COVERAGE=0

matrix:
  exclude:
    - env: TYPO3_BRANCH=master COVERAGE=0
      php: 5.3
    - env: TYPO3_BRANCH=master COVERAGE=0
      php: 5.4
  include:
    - php: 5.5
      env: TYPO3_BRANCH=TYPO3_6-2 COVERAGE=1

notifications:
  email:
    recipients:
      - secure: "oragnT/ylb5mUG+qyuLYIc/dE5RWQUl5+S292i0YNj+wqq+4OpQ6NVf4nGRyg52S87y5NiBmNbsVf2z+M5rKYhM06mA/PjhFYb0uL3ki4vzMzijszWV/TAZ3+lF21KquZ9puOS6Q5GSzJ5OHg0q3APbp/6Uq7N3FcOpnMbGHjPJQYYUi0M7B2l9x/VRF3Qjk4oNsMKYbYnUstHVQcu9M6yXVxxKMzcBQfXAdERX6Qcl/kprZi9j5LfttD5h8BdKfqy637+3hXFjUHlLZ4GTzWYRd7ilQUKVa4AwZsJTDTrYdSI97spfSEDTQW2jEPwB2s8dQwmx9rO+T23KFLQqZ+wMhJzDarF/GK9cLl96vN95qaLf7gZrWeiSHCQkdoDEhrLPhzpHT5GBtRfG5pqW5uXcMjeeYRiy3jl2If+NAT6x4KEZCamNXB3B0mUW3PWfiB20eq6ssly2J/JOqDN+Wa8/ew3MZu2kD396o8utSLxT3c4xVV/DBuhnHNZSOVcK/G110WnpupMZaMo92A/oO0oY7WZ6zxmtr1WiCizpLmhKyMp41/WTLTt2wEBRibBhvKAXWY4ozvqRdGvVktDruI2y5VVMPIfUYZOLDop2dJDxyshMsyFNiuQ62Ds/Zxn9sb3WQ4Yd4dOGXgYFWwRDFBE+EoO7iRQ58yt7k5C1kfHI="
      - secure: "mdgMU7cEvUEVaQODAhsGzBMU4F/QMEytv8k8vHiLrRNvcWt3RZ+I49bHWdWLmS5tM96mwUmLKwNlvec6Tb8q4P8aguTZfKYWvE2yZKVT2nL4TjGrLViegbbsF+ckfKNEfqBpEC4Bj3Pj9IF56TSbG8kOxCZXBMitoAMWZ4bsb4iNUZZs1SUcH9nIuTC8JecylXY/IFDa11IxMbV2/wgWnEYQzUGiZrMqGQKAf0/ELEgDQz+iud9gKj6i/3mLEoJz5D3WkJUuLjcxSx+TZvbjAEeBf8z4gnhQvv0VVCWX5DfGvQQj9OWN9qudwkRFLpopG26MJ15RjQD82z32ICKQZEF4nUsTV3ngyfwup3Yo/x+WpfYPunlZAAls/z/q5fkbNsZt2OJXMX4Ce1BYaM4jUNMx6ynBX8Sa2+kqgS56tIkRmAxSaIq1BkLUwKoLhoS7N2W4z/V2ANeKfpARLurF6lUP5zMdQg6pwEWTe17WMBsPQNnrB4mXAL0ztwund7kYKrvQejGRpvtlEvvvl6Y4io7eb1w1L2k11niWKx2n3VYoG+m04ZQ1p2zZ82eX1E19jM9vp33rqjhhI0U0TwlnXBbHuIoDAFCqSb1jKnnILesGctiaJtF086qIHtfkDyZ+PKRebAOM+mgk3HdhWBdPOwx2qYDnqaLKxOZ/cI31+5k="
    on_success: always
    on_failure: always

before_script:
  - sudo apt-get install parallel
  - composer self-update
  - composer install

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --colors -c typo3_src/typo3/sysext/core/Build/UnitTests.xml --bootstrap typo3_src/typo3/sysext/core/Build/UnitTestsBootstrap.php Tests/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c typo3_src/typo3/sysext/core/Build/UnitTests.xml --bootstrap typo3_src/typo3/sysext/core/Build/UnitTestsBootstrap.php Tests/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      cp -R typo3conf/ext/asdis/.git .
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    fi
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/asdis -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "
