<?php

class Tx_Asdis_Content_FilterService {

	/**
	 * Applies the configured filters to the given paths.
	 * This includes removement of auto-generated files (those whose filename
	 * contains a '?') and the exclude filters.
	 *
	 * @param array $paths
	 * @return array The filtered path list.
	 */
	public function applyFiltersToFilePaths(array $paths) {

		$filteredPaths   = array();
		$paths           = $this->removeAutoGeneratedFilePaths($paths);
		$excludePatterns = $this->configuration->getExcludePatterns();

		if (sizeof($paths) > 0) {
			foreach ($paths as $path) {
				$slashPos = strpos($path, "/");
				if ($slashPos === 0) {
					$path = substr($path, 1);
				}
				$numExcludePatterns = sizeof($excludePatterns);
				$exclude            = FALSE;
				if ($this->fileManager->containsProtocol($path)) {
					$exclude = TRUE;
				}
				if (sizeof($excludePatterns) > 0) {
					for ($i = 0; $i < $numExcludePatterns && !$exclude; $i++) {
						if (preg_match($excludePatterns[$i], $path) === 1) {
							$exclude = TRUE;
						}
					}
				}
				if ($exclude === FALSE) {
					$filteredPaths[] = $path;
				}
			}
		} else {
			$filteredPaths = $paths;
		}

		return $filteredPaths;
	}
}